### ISSUE TITLE
Not an issue, but a question

### ISSUE THREAD

**Issue by AnubhavMadhav-BothOfUs** [vinaypatil03/Covid-19-Vaccine-Tracker-India-Django-App#1]
Did you tried deploying it to heroku or somewhere else?

**Comment by vinaypatil03** [comment]
> Did you tried deploying it to heroku or somewhere else?

I have deployed it on Heroku, https://findmyvaccine.herokuapp.com/ but the Cowin API do not work on it. As heroku uses US servers and the Cowin Site does not accept any requests other than indian servers.
